// Code generated by generator; DO NOT EDIT. See: github.com/dorser/seccomp-ebpf/tools/tracepoints

package tracepoints

type SyscallTracepoint struct {
	Enter bool
	Exit  bool
}

func SyscallHasEnterTracepoint(syscall string) bool {
	tracepoints, exists := tracepoints[syscall]
	if exists {
		return tracepoints.Enter
	}
	return false
}

func SyscallHasExitTracepoint(syscall string) bool {
	tracepoints, exists := tracepoints[syscall]
	if exists {
		return tracepoints.Exit
	}
	return false
}

func SyscallHasTracepoint(syscall string) bool {
	_, exists := tracepoints[syscall]
	return exists
}

var tracepoints = map[string]SyscallTracepoint{
	"accept": {
		Enter: true,
		Exit: true,
	},
	"accept4": {
		Enter: true,
		Exit: true,
	},
	"access": {
		Enter: true,
		Exit: true,
	},
	"acct": {
		Enter: true,
		Exit: true,
	},
	"add_key": {
		Enter: true,
		Exit: true,
	},
	"adjtimex": {
		Enter: true,
		Exit: true,
	},
	"alarm": {
		Enter: true,
		Exit: true,
	},
	"arch_prctl": {
		Enter: true,
		Exit: true,
	},
	"bind": {
		Enter: true,
		Exit: true,
	},
	"bpf": {
		Enter: true,
		Exit: true,
	},
	"brk": {
		Enter: true,
		Exit: true,
	},
	"cachestat": {
		Enter: true,
		Exit: true,
	},
	"capget": {
		Enter: true,
		Exit: true,
	},
	"capset": {
		Enter: true,
		Exit: true,
	},
	"chdir": {
		Enter: true,
		Exit: true,
	},
	"chmod": {
		Enter: true,
		Exit: true,
	},
	"chown": {
		Enter: true,
		Exit: true,
	},
	"chroot": {
		Enter: true,
		Exit: true,
	},
	"clock_adjtime": {
		Enter: true,
		Exit: true,
	},
	"clock_getres": {
		Enter: true,
		Exit: true,
	},
	"clock_gettime": {
		Enter: true,
		Exit: true,
	},
	"clock_nanosleep": {
		Enter: true,
		Exit: true,
	},
	"clock_settime": {
		Enter: true,
		Exit: true,
	},
	"clone": {
		Enter: true,
		Exit: true,
	},
	"clone3": {
		Enter: true,
		Exit: true,
	},
	"close": {
		Enter: true,
		Exit: true,
	},
	"close_range": {
		Enter: true,
		Exit: true,
	},
	"connect": {
		Enter: true,
		Exit: true,
	},
	"copy_file_range": {
		Enter: true,
		Exit: true,
	},
	"creat": {
		Enter: true,
		Exit: true,
	},
	"delete_module": {
		Enter: true,
		Exit: true,
	},
	"dup": {
		Enter: true,
		Exit: true,
	},
	"dup2": {
		Enter: true,
		Exit: true,
	},
	"dup3": {
		Enter: true,
		Exit: true,
	},
	"epoll_create": {
		Enter: true,
		Exit: true,
	},
	"epoll_create1": {
		Enter: true,
		Exit: true,
	},
	"epoll_ctl": {
		Enter: true,
		Exit: true,
	},
	"epoll_pwait": {
		Enter: true,
		Exit: true,
	},
	"epoll_pwait2": {
		Enter: true,
		Exit: true,
	},
	"epoll_wait": {
		Enter: true,
		Exit: true,
	},
	"eventfd": {
		Enter: true,
		Exit: true,
	},
	"eventfd2": {
		Enter: true,
		Exit: true,
	},
	"execve": {
		Enter: true,
		Exit: true,
	},
	"execveat": {
		Enter: true,
		Exit: true,
	},
	"exit": {
		Enter: true,
		Exit: true,
	},
	"exit_group": {
		Enter: true,
		Exit: true,
	},
	"faccessat": {
		Enter: true,
		Exit: true,
	},
	"faccessat2": {
		Enter: true,
		Exit: true,
	},
	"fadvise64": {
		Enter: true,
		Exit: true,
	},
	"fallocate": {
		Enter: true,
		Exit: true,
	},
	"fanotify_init": {
		Enter: true,
		Exit: true,
	},
	"fanotify_mark": {
		Enter: true,
		Exit: true,
	},
	"fchdir": {
		Enter: true,
		Exit: true,
	},
	"fchmod": {
		Enter: true,
		Exit: true,
	},
	"fchmodat": {
		Enter: true,
		Exit: true,
	},
	"fchmodat2": {
		Enter: true,
		Exit: true,
	},
	"fchown": {
		Enter: true,
		Exit: true,
	},
	"fchownat": {
		Enter: true,
		Exit: true,
	},
	"fcntl": {
		Enter: true,
		Exit: true,
	},
	"fdatasync": {
		Enter: true,
		Exit: true,
	},
	"fgetxattr": {
		Enter: true,
		Exit: true,
	},
	"finit_module": {
		Enter: true,
		Exit: true,
	},
	"flistxattr": {
		Enter: true,
		Exit: true,
	},
	"flock": {
		Enter: true,
		Exit: true,
	},
	"fork": {
		Enter: true,
		Exit: true,
	},
	"fremovexattr": {
		Enter: true,
		Exit: true,
	},
	"fsconfig": {
		Enter: true,
		Exit: true,
	},
	"fsetxattr": {
		Enter: true,
		Exit: true,
	},
	"fsmount": {
		Enter: true,
		Exit: true,
	},
	"fsopen": {
		Enter: true,
		Exit: true,
	},
	"fspick": {
		Enter: true,
		Exit: true,
	},
	"fstatfs": {
		Enter: true,
		Exit: true,
	},
	"fsync": {
		Enter: true,
		Exit: true,
	},
	"ftruncate": {
		Enter: true,
		Exit: true,
	},
	"futex": {
		Enter: true,
		Exit: true,
	},
	"futex_requeue": {
		Enter: true,
		Exit: true,
	},
	"futex_wait": {
		Enter: true,
		Exit: true,
	},
	"futex_waitv": {
		Enter: true,
		Exit: true,
	},
	"futex_wake": {
		Enter: true,
		Exit: true,
	},
	"futimesat": {
		Enter: true,
		Exit: true,
	},
	"get_mempolicy": {
		Enter: true,
		Exit: true,
	},
	"get_robust_list": {
		Enter: true,
		Exit: true,
	},
	"getcpu": {
		Enter: true,
		Exit: true,
	},
	"getcwd": {
		Enter: true,
		Exit: true,
	},
	"getdents": {
		Enter: true,
		Exit: true,
	},
	"getdents64": {
		Enter: true,
		Exit: true,
	},
	"getegid": {
		Enter: true,
		Exit: true,
	},
	"geteuid": {
		Enter: true,
		Exit: true,
	},
	"getgid": {
		Enter: true,
		Exit: true,
	},
	"getgroups": {
		Enter: true,
		Exit: true,
	},
	"getitimer": {
		Enter: true,
		Exit: true,
	},
	"getpeername": {
		Enter: true,
		Exit: true,
	},
	"getpgid": {
		Enter: true,
		Exit: true,
	},
	"getpgrp": {
		Enter: true,
		Exit: true,
	},
	"getpid": {
		Enter: true,
		Exit: true,
	},
	"getppid": {
		Enter: true,
		Exit: true,
	},
	"getpriority": {
		Enter: true,
		Exit: true,
	},
	"getrandom": {
		Enter: true,
		Exit: true,
	},
	"getresgid": {
		Enter: true,
		Exit: true,
	},
	"getresuid": {
		Enter: true,
		Exit: true,
	},
	"getrlimit": {
		Enter: true,
		Exit: true,
	},
	"getrusage": {
		Enter: true,
		Exit: true,
	},
	"getsid": {
		Enter: true,
		Exit: true,
	},
	"getsockname": {
		Enter: true,
		Exit: true,
	},
	"getsockopt": {
		Enter: true,
		Exit: true,
	},
	"gettid": {
		Enter: true,
		Exit: true,
	},
	"gettimeofday": {
		Enter: true,
		Exit: true,
	},
	"getuid": {
		Enter: true,
		Exit: true,
	},
	"getxattr": {
		Enter: true,
		Exit: true,
	},
	"init_module": {
		Enter: true,
		Exit: true,
	},
	"inotify_add_watch": {
		Enter: true,
		Exit: true,
	},
	"inotify_init": {
		Enter: true,
		Exit: true,
	},
	"inotify_init1": {
		Enter: true,
		Exit: true,
	},
	"inotify_rm_watch": {
		Enter: true,
		Exit: true,
	},
	"io_cancel": {
		Enter: true,
		Exit: true,
	},
	"io_destroy": {
		Enter: true,
		Exit: true,
	},
	"io_getevents": {
		Enter: true,
		Exit: true,
	},
	"io_pgetevents": {
		Enter: true,
		Exit: true,
	},
	"io_setup": {
		Enter: true,
		Exit: true,
	},
	"io_submit": {
		Enter: true,
		Exit: true,
	},
	"io_uring_enter": {
		Enter: true,
		Exit: true,
	},
	"io_uring_register": {
		Enter: true,
		Exit: true,
	},
	"io_uring_setup": {
		Enter: true,
		Exit: true,
	},
	"ioctl": {
		Enter: true,
		Exit: true,
	},
	"ioperm": {
		Enter: true,
		Exit: true,
	},
	"iopl": {
		Enter: true,
		Exit: true,
	},
	"ioprio_get": {
		Enter: true,
		Exit: true,
	},
	"ioprio_set": {
		Enter: true,
		Exit: true,
	},
	"kcmp": {
		Enter: true,
		Exit: true,
	},
	"kexec_file_load": {
		Enter: true,
		Exit: true,
	},
	"kexec_load": {
		Enter: true,
		Exit: true,
	},
	"keyctl": {
		Enter: true,
		Exit: true,
	},
	"kill": {
		Enter: true,
		Exit: true,
	},
	"landlock_add_rule": {
		Enter: true,
		Exit: true,
	},
	"landlock_create_ruleset": {
		Enter: true,
		Exit: true,
	},
	"landlock_restrict_self": {
		Enter: true,
		Exit: true,
	},
	"lchown": {
		Enter: true,
		Exit: true,
	},
	"lgetxattr": {
		Enter: true,
		Exit: true,
	},
	"link": {
		Enter: true,
		Exit: true,
	},
	"linkat": {
		Enter: true,
		Exit: true,
	},
	"listen": {
		Enter: true,
		Exit: true,
	},
	"listmount": {
		Enter: true,
		Exit: true,
	},
	"listxattr": {
		Enter: true,
		Exit: true,
	},
	"llistxattr": {
		Enter: true,
		Exit: true,
	},
	"lremovexattr": {
		Enter: true,
		Exit: true,
	},
	"lseek": {
		Enter: true,
		Exit: true,
	},
	"lsetxattr": {
		Enter: true,
		Exit: true,
	},
	"lsm_get_self_attr": {
		Enter: true,
		Exit: true,
	},
	"lsm_list_modules": {
		Enter: true,
		Exit: true,
	},
	"lsm_set_self_attr": {
		Enter: true,
		Exit: true,
	},
	"madvise": {
		Enter: true,
		Exit: true,
	},
	"map_shadow_stack": {
		Enter: true,
		Exit: true,
	},
	"mbind": {
		Enter: true,
		Exit: true,
	},
	"membarrier": {
		Enter: true,
		Exit: true,
	},
	"memfd_create": {
		Enter: true,
		Exit: true,
	},
	"memfd_secret": {
		Enter: true,
		Exit: true,
	},
	"migrate_pages": {
		Enter: true,
		Exit: true,
	},
	"mincore": {
		Enter: true,
		Exit: true,
	},
	"mkdir": {
		Enter: true,
		Exit: true,
	},
	"mkdirat": {
		Enter: true,
		Exit: true,
	},
	"mknod": {
		Enter: true,
		Exit: true,
	},
	"mknodat": {
		Enter: true,
		Exit: true,
	},
	"mlock": {
		Enter: true,
		Exit: true,
	},
	"mlock2": {
		Enter: true,
		Exit: true,
	},
	"mlockall": {
		Enter: true,
		Exit: true,
	},
	"mmap": {
		Enter: true,
		Exit: true,
	},
	"modify_ldt": {
		Enter: true,
		Exit: true,
	},
	"mount": {
		Enter: true,
		Exit: true,
	},
	"mount_setattr": {
		Enter: true,
		Exit: true,
	},
	"move_mount": {
		Enter: true,
		Exit: true,
	},
	"move_pages": {
		Enter: true,
		Exit: true,
	},
	"mprotect": {
		Enter: true,
		Exit: true,
	},
	"mq_getsetattr": {
		Enter: true,
		Exit: true,
	},
	"mq_notify": {
		Enter: true,
		Exit: true,
	},
	"mq_open": {
		Enter: true,
		Exit: true,
	},
	"mq_timedreceive": {
		Enter: true,
		Exit: true,
	},
	"mq_timedsend": {
		Enter: true,
		Exit: true,
	},
	"mq_unlink": {
		Enter: true,
		Exit: true,
	},
	"mremap": {
		Enter: true,
		Exit: true,
	},
	"msgctl": {
		Enter: true,
		Exit: true,
	},
	"msgget": {
		Enter: true,
		Exit: true,
	},
	"msgrcv": {
		Enter: true,
		Exit: true,
	},
	"msgsnd": {
		Enter: true,
		Exit: true,
	},
	"msync": {
		Enter: true,
		Exit: true,
	},
	"munlock": {
		Enter: true,
		Exit: true,
	},
	"munlockall": {
		Enter: true,
		Exit: true,
	},
	"munmap": {
		Enter: true,
		Exit: true,
	},
	"name_to_handle_at": {
		Enter: true,
		Exit: true,
	},
	"nanosleep": {
		Enter: true,
		Exit: true,
	},
	"newfstat": {
		Enter: true,
		Exit: true,
	},
	"newfstatat": {
		Enter: true,
		Exit: true,
	},
	"newlstat": {
		Enter: true,
		Exit: true,
	},
	"newstat": {
		Enter: true,
		Exit: true,
	},
	"newuname": {
		Enter: true,
		Exit: true,
	},
	"open": {
		Enter: true,
		Exit: true,
	},
	"open_by_handle_at": {
		Enter: true,
		Exit: true,
	},
	"open_tree": {
		Enter: true,
		Exit: true,
	},
	"openat": {
		Enter: true,
		Exit: true,
	},
	"openat2": {
		Enter: true,
		Exit: true,
	},
	"pause": {
		Enter: true,
		Exit: true,
	},
	"perf_event_open": {
		Enter: true,
		Exit: true,
	},
	"personality": {
		Enter: true,
		Exit: true,
	},
	"pidfd_getfd": {
		Enter: true,
		Exit: true,
	},
	"pidfd_open": {
		Enter: true,
		Exit: true,
	},
	"pidfd_send_signal": {
		Enter: true,
		Exit: true,
	},
	"pipe": {
		Enter: true,
		Exit: true,
	},
	"pipe2": {
		Enter: true,
		Exit: true,
	},
	"pivot_root": {
		Enter: true,
		Exit: true,
	},
	"pkey_alloc": {
		Enter: true,
		Exit: true,
	},
	"pkey_free": {
		Enter: true,
		Exit: true,
	},
	"pkey_mprotect": {
		Enter: true,
		Exit: true,
	},
	"poll": {
		Enter: true,
		Exit: true,
	},
	"ppoll": {
		Enter: true,
		Exit: true,
	},
	"prctl": {
		Enter: true,
		Exit: true,
	},
	"pread64": {
		Enter: true,
		Exit: true,
	},
	"preadv": {
		Enter: true,
		Exit: true,
	},
	"preadv2": {
		Enter: true,
		Exit: true,
	},
	"prlimit64": {
		Enter: true,
		Exit: true,
	},
	"process_madvise": {
		Enter: true,
		Exit: true,
	},
	"process_mrelease": {
		Enter: true,
		Exit: true,
	},
	"process_vm_readv": {
		Enter: true,
		Exit: true,
	},
	"process_vm_writev": {
		Enter: true,
		Exit: true,
	},
	"pselect6": {
		Enter: true,
		Exit: true,
	},
	"ptrace": {
		Enter: true,
		Exit: true,
	},
	"pwrite64": {
		Enter: true,
		Exit: true,
	},
	"pwritev": {
		Enter: true,
		Exit: true,
	},
	"pwritev2": {
		Enter: true,
		Exit: true,
	},
	"quotactl": {
		Enter: true,
		Exit: true,
	},
	"quotactl_fd": {
		Enter: true,
		Exit: true,
	},
	"read": {
		Enter: true,
		Exit: true,
	},
	"readahead": {
		Enter: true,
		Exit: true,
	},
	"readlink": {
		Enter: true,
		Exit: true,
	},
	"readlinkat": {
		Enter: true,
		Exit: true,
	},
	"readv": {
		Enter: true,
		Exit: true,
	},
	"reboot": {
		Enter: true,
		Exit: true,
	},
	"recvfrom": {
		Enter: true,
		Exit: true,
	},
	"recvmmsg": {
		Enter: true,
		Exit: true,
	},
	"recvmsg": {
		Enter: true,
		Exit: true,
	},
	"remap_file_pages": {
		Enter: true,
		Exit: true,
	},
	"removexattr": {
		Enter: true,
		Exit: true,
	},
	"rename": {
		Enter: true,
		Exit: true,
	},
	"renameat": {
		Enter: true,
		Exit: true,
	},
	"renameat2": {
		Enter: true,
		Exit: true,
	},
	"request_key": {
		Enter: true,
		Exit: true,
	},
	"restart_syscall": {
		Enter: true,
		Exit: true,
	},
	"rmdir": {
		Enter: true,
		Exit: true,
	},
	"rseq": {
		Enter: true,
		Exit: true,
	},
	"rt_sigaction": {
		Enter: true,
		Exit: true,
	},
	"rt_sigpending": {
		Enter: true,
		Exit: true,
	},
	"rt_sigprocmask": {
		Enter: true,
		Exit: true,
	},
	"rt_sigqueueinfo": {
		Enter: true,
		Exit: true,
	},
	"rt_sigreturn": {
		Enter: true,
		Exit: true,
	},
	"rt_sigsuspend": {
		Enter: true,
		Exit: true,
	},
	"rt_sigtimedwait": {
		Enter: true,
		Exit: true,
	},
	"rt_tgsigqueueinfo": {
		Enter: true,
		Exit: true,
	},
	"sched_get_priority_max": {
		Enter: true,
		Exit: true,
	},
	"sched_get_priority_min": {
		Enter: true,
		Exit: true,
	},
	"sched_getaffinity": {
		Enter: true,
		Exit: true,
	},
	"sched_getattr": {
		Enter: true,
		Exit: true,
	},
	"sched_getparam": {
		Enter: true,
		Exit: true,
	},
	"sched_getscheduler": {
		Enter: true,
		Exit: true,
	},
	"sched_rr_get_interval": {
		Enter: true,
		Exit: true,
	},
	"sched_setaffinity": {
		Enter: true,
		Exit: true,
	},
	"sched_setattr": {
		Enter: true,
		Exit: true,
	},
	"sched_setparam": {
		Enter: true,
		Exit: true,
	},
	"sched_setscheduler": {
		Enter: true,
		Exit: true,
	},
	"sched_yield": {
		Enter: true,
		Exit: true,
	},
	"seccomp": {
		Enter: true,
		Exit: true,
	},
	"select": {
		Enter: true,
		Exit: true,
	},
	"semctl": {
		Enter: true,
		Exit: true,
	},
	"semget": {
		Enter: true,
		Exit: true,
	},
	"semop": {
		Enter: true,
		Exit: true,
	},
	"semtimedop": {
		Enter: true,
		Exit: true,
	},
	"sendfile64": {
		Enter: true,
		Exit: true,
	},
	"sendmmsg": {
		Enter: true,
		Exit: true,
	},
	"sendmsg": {
		Enter: true,
		Exit: true,
	},
	"sendto": {
		Enter: true,
		Exit: true,
	},
	"set_mempolicy": {
		Enter: true,
		Exit: true,
	},
	"set_mempolicy_home_node": {
		Enter: true,
		Exit: true,
	},
	"set_robust_list": {
		Enter: true,
		Exit: true,
	},
	"set_tid_address": {
		Enter: true,
		Exit: true,
	},
	"setdomainname": {
		Enter: true,
		Exit: true,
	},
	"setfsgid": {
		Enter: true,
		Exit: true,
	},
	"setfsuid": {
		Enter: true,
		Exit: true,
	},
	"setgid": {
		Enter: true,
		Exit: true,
	},
	"setgroups": {
		Enter: true,
		Exit: true,
	},
	"sethostname": {
		Enter: true,
		Exit: true,
	},
	"setitimer": {
		Enter: true,
		Exit: true,
	},
	"setns": {
		Enter: true,
		Exit: true,
	},
	"setpgid": {
		Enter: true,
		Exit: true,
	},
	"setpriority": {
		Enter: true,
		Exit: true,
	},
	"setregid": {
		Enter: true,
		Exit: true,
	},
	"setresgid": {
		Enter: true,
		Exit: true,
	},
	"setresuid": {
		Enter: true,
		Exit: true,
	},
	"setreuid": {
		Enter: true,
		Exit: true,
	},
	"setrlimit": {
		Enter: true,
		Exit: true,
	},
	"setsid": {
		Enter: true,
		Exit: true,
	},
	"setsockopt": {
		Enter: true,
		Exit: true,
	},
	"settimeofday": {
		Enter: true,
		Exit: true,
	},
	"setuid": {
		Enter: true,
		Exit: true,
	},
	"setxattr": {
		Enter: true,
		Exit: true,
	},
	"shmat": {
		Enter: true,
		Exit: true,
	},
	"shmctl": {
		Enter: true,
		Exit: true,
	},
	"shmdt": {
		Enter: true,
		Exit: true,
	},
	"shmget": {
		Enter: true,
		Exit: true,
	},
	"shutdown": {
		Enter: true,
		Exit: true,
	},
	"sigaltstack": {
		Enter: true,
		Exit: true,
	},
	"signalfd": {
		Enter: true,
		Exit: true,
	},
	"signalfd4": {
		Enter: true,
		Exit: true,
	},
	"socket": {
		Enter: true,
		Exit: true,
	},
	"socketpair": {
		Enter: true,
		Exit: true,
	},
	"splice": {
		Enter: true,
		Exit: true,
	},
	"statfs": {
		Enter: true,
		Exit: true,
	},
	"statmount": {
		Enter: true,
		Exit: true,
	},
	"statx": {
		Enter: true,
		Exit: true,
	},
	"swapoff": {
		Enter: true,
		Exit: true,
	},
	"swapon": {
		Enter: true,
		Exit: true,
	},
	"symlink": {
		Enter: true,
		Exit: true,
	},
	"symlinkat": {
		Enter: true,
		Exit: true,
	},
	"sync": {
		Enter: true,
		Exit: true,
	},
	"sync_file_range": {
		Enter: true,
		Exit: true,
	},
	"syncfs": {
		Enter: true,
		Exit: true,
	},
	"sysfs": {
		Enter: true,
		Exit: true,
	},
	"sysinfo": {
		Enter: true,
		Exit: true,
	},
	"syslog": {
		Enter: true,
		Exit: true,
	},
	"tee": {
		Enter: true,
		Exit: true,
	},
	"tgkill": {
		Enter: true,
		Exit: true,
	},
	"time": {
		Enter: true,
		Exit: true,
	},
	"timer_create": {
		Enter: true,
		Exit: true,
	},
	"timer_delete": {
		Enter: true,
		Exit: true,
	},
	"timer_getoverrun": {
		Enter: true,
		Exit: true,
	},
	"timer_gettime": {
		Enter: true,
		Exit: true,
	},
	"timer_settime": {
		Enter: true,
		Exit: true,
	},
	"timerfd_create": {
		Enter: true,
		Exit: true,
	},
	"timerfd_gettime": {
		Enter: true,
		Exit: true,
	},
	"timerfd_settime": {
		Enter: true,
		Exit: true,
	},
	"times": {
		Enter: true,
		Exit: true,
	},
	"tkill": {
		Enter: true,
		Exit: true,
	},
	"truncate": {
		Enter: true,
		Exit: true,
	},
	"umask": {
		Enter: true,
		Exit: true,
	},
	"umount": {
		Enter: true,
		Exit: true,
	},
	"unlink": {
		Enter: true,
		Exit: true,
	},
	"unlinkat": {
		Enter: true,
		Exit: true,
	},
	"unshare": {
		Enter: true,
		Exit: true,
	},
	"userfaultfd": {
		Enter: true,
		Exit: true,
	},
	"ustat": {
		Enter: true,
		Exit: true,
	},
	"utime": {
		Enter: true,
		Exit: true,
	},
	"utimensat": {
		Enter: true,
		Exit: true,
	},
	"utimes": {
		Enter: true,
		Exit: true,
	},
	"vfork": {
		Enter: true,
		Exit: true,
	},
	"vhangup": {
		Enter: true,
		Exit: true,
	},
	"vmsplice": {
		Enter: true,
		Exit: true,
	},
	"wait4": {
		Enter: true,
		Exit: true,
	},
	"waitid": {
		Enter: true,
		Exit: true,
	},
	"write": {
		Enter: true,
		Exit: true,
	},
	"writev": {
		Enter: true,
		Exit: true,
	},
}
